# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

import comtypes

import addonHandler
import api
import appModuleHandler
import controlTypes
import gui
from NVDAObjects.behaviors import EditableTextWithAutoSelectDetection
from NVDAObjects.UIA import UIA, UIATextInfo
import ui

from . import beeps
from .interface import MSEdgeDiscardAnnouncementsPanel
from .settings import EventConfigs, Mode, loadNotificationConfigs
from .sounds import playFile

addonHandler.initTranslation()

scriptSet = False


class CustomUIATextInfo(UIATextInfo):
    def compareEndPoints(self, *args, **kwargs):
        try:
            return super().compareEndPoints(*args, **kwargs)
        except comtypes.COMError:
            return 0


class CustomEditableTextWithAutoSelectDetection(EditableTextWithAutoSelectDetection):
    TextInfo = CustomUIATextInfo

    def event_caret(self, *args, **kwargs):
        try:
            return super().event_caret(*args, **kwargs)
        except comtypes.COMError:
            pass


class AppModule(appModuleHandler.AppModule):
    eventConfigs = EventConfigs()

    def __init__(self, processID, appName):
        super().__init__(processID, appName)
        self.loadEventConfigs()
        categoryClasses = gui.settingsDialogs.NVDASettingsDialog.categoryClasses
        if MSEdgeDiscardAnnouncementsPanel not in categoryClasses:
            categoryClasses.append(MSEdgeDiscardAnnouncementsPanel)

    def terminate(self):
        super().terminate()
        categoryClasses = gui.settingsDialogs.NVDASettingsDialog.categoryClasses
        if MSEdgeDiscardAnnouncementsPanel in categoryClasses:
            gui.settingsDialogs.NVDASettingsDialog.categoryClasses.remove(MSEdgeDiscardAnnouncementsPanel)

    def chooseNVDAObjectOverlayClasses(self, obj, clsList):
        if isinstance(obj, UIA) and (
            (
                obj.role == controlTypes.role.Role.EDITABLETEXT
                and obj.UIAElement.CurrentClassName == "OmniboxViewViews"
            )
            or obj.UIAElement.CurrentClassName == "Textfield"
        ):
            clsList.insert(0, CustomEditableTextWithAutoSelectDetection)

    def event_NVDAObject_init(self, obj):
        if self.eventConfigs.ShowSuggestions.mode != Mode.OFF:
            return
        if isinstance(obj, UIA) and obj.UIAElement.CurrentClassName == "OmniboxResultView":
            obj.isDescendantOf = lambda obj: False

    def loadEventConfigs(self):
        self.eventConfigs = loadNotificationConfigs()

    def event_appModule_gainFocus(self):
        self.loadEventConfigs()

    def event_UIA_notification(self, obj, nextHandler, activityId=None, **kwargs):
        eventConfig = self.eventConfigs.get(activityId)
        if eventConfig is None:
            nextHandler()
            return
        if eventConfig.mode == Mode.OFF:
            return
        if "HubDownloads" in activityId:
            foreground = api.getForegroundObject()
            if obj.appModule == foreground.appModule and not obj.isDescendantOf(foreground):
                return
        if eventConfig.mode == Mode.BEEPS:
            beeps.playPattern(eventConfig.beepPattern)
            return
        if eventConfig.mode == Mode.WAVE:
            if not playFile(eventConfig.waveFile, eventConfig.waveVolume):
                nextHandler()
            return
        if eventConfig.useCustomMessage and eventConfig.customMessage:
            ui.message(eventConfig.customMessage)
            return
        nextHandler()
