# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

from typing import NamedTuple

from logHandler import log
import tones
import wx

MIN_FREQUENCY = 50
MAX_FREQUENCY = 5000
MIN_LENGTH = 10
MAX_LENGTH = 5000
MAX_PAUSE = 5000
MAX_VOLUME = 100


class BeepStep(NamedTuple):
    frequency: int = 440
    length: int = 60
    leftVolume: int = 50
    rightVolume: int = 50
    pause: int = 0

    def serialize(self):
        return ",".join(str(field) for field in self)

    @classmethod
    def deserialize(cls, value):
        fields = value.split(",")
        if len(fields) != len(cls._fields):
            raise ValueError(f"Expected {len(cls._fields)} fields, got {value!r}")
        return cls(*(int(field) for field in fields))


DEFAULT_STEP = BeepStep()


def serializePattern(pattern):
    return [step.serialize() for step in pattern]


def deserializePattern(value):
    pattern = []
    for item in value:
        try:
            pattern.append(BeepStep.deserialize(item))
        except ValueError:
            log.warning(f"Discarding malformed beep pattern step {item!r}", exc_info=True)
    return pattern


def playPattern(pattern):
    delay = 0
    for step in pattern or [DEFAULT_STEP]:
        if delay:
            wx.CallLater(delay, tones.beep, step.frequency, step.length, step.leftVolume, step.rightVolume)
        else:
            tones.beep(step.frequency, step.length, step.leftVolume, step.rightVolume)
        delay += step.length + step.pause
