# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

from enum import StrEnum
from typing import Callable, NamedTuple

import addonHandler
import config
from logHandler import log

from .beeps import deserializePattern, serializePattern

addonHandler.initTranslation()

addonInstance = addonHandler.getCodeAddon()
addonName = addonInstance.name
addonSummary = addonInstance.manifest["summary"]


class Mode(StrEnum):
    OFF = "off"
    SPEAK = "speak"
    BEEPS = "beeps"
    WAVE = "wave"

    @property
    def displayString(self):
        return MODE_LABELS[self]

    @classmethod
    def fromConfig(cls, value):
        try:
            return cls(value)
        except ValueError:
            log.warning(f"Unknown notification action {value!r}, falling back to {cls.SPEAK.value}")
            return cls.SPEAK


MODES = tuple(Mode)

MODE_LABELS = {
    # Translators: An action for a notification, meaning that it is not reported at all.
    Mode.OFF: _("Off"),
    # Translators: An action for a notification, meaning that it is spoken.
    Mode.SPEAK: _("Speak"),
    # Translators: An action for a notification, meaning that it is replaced by beeps.
    Mode.BEEPS: _("Beeps"),
    # Translators: An action for a notification, meaning that it is replaced by a wave file.
    Mode.WAVE: _("Wave file"),
}


class Kind(StrEnum):
    ACTION = "action"
    TOGGLE = "toggle"


class Settings(NamedTuple):
    configKey: str
    label: str
    defaultMode: Mode = Mode.SPEAK
    activityIDs: tuple[str, ...] = ()
    kind: Kind = Kind.ACTION

    @property
    def notificationIDs(self):
        return self.activityIDs or (self.configKey,)

    @property
    def configSpec(self):
        return {field.name: field.specFor(self) for field in FIELDS}


settingItems = [
    Settings("PageLoading", _("Loading of pages"), Mode.OFF),
    Settings("RefreshingPage", _("Page refresh"), Mode.OFF),
    Settings("ClosingTab", _("Closing of tab"), Mode.OFF),
    Settings("OpeningNewTab", _("Opening of new tab"), Mode.OFF),
    Settings("OpeningWindow", _("Window opening"), Mode.OFF),
    Settings("OpeningInPrivateWindow", _("Opening of inprivate window"), Mode.OFF),
    Settings("HubDownloadsNewDownload", _("Starting file download"), Mode.SPEAK),
    Settings("HubDownloadsCompleteState", _("Download completion"), Mode.SPEAK),
    Settings("GoingBack", _("Navigating back"), Mode.OFF),
    Settings("GoingForward", _("Navigating forward"), Mode.OFF),
    Settings("CantGoBack", _("No previous page to navigate"), Mode.OFF),
    Settings("CantGoForward", _("No next page to navigate"), Mode.OFF),
    Settings("ToolbarButtonRemoved", _("Removing toolbar buttons"), Mode.OFF),
    Settings("SearchMode", _("Search mode"), Mode.OFF),
    Settings("SearchModeAvailable", _("Availability of search mode"), Mode.OFF),
    Settings("NotificationAppear", _("Appearing of notifications"), Mode.OFF),
    Settings(
        "HubDownloadsInProgressState",
        _("Progress state of current download"),
        Mode.OFF,
        ("HubDownloadsInProgressState", "HubDownloadsIndividualProgressState"),
    ),
    Settings(
        "HubDownloadsIndeterminateProgressState",
        _("Indeterminate progress state of current download"),
        Mode.OFF,
    ),
    Settings(
        "AutofillSuggestions",
        _("Announce autofill suggestions"),
        Mode.OFF,
        kind=Kind.TOGGLE,
    ),
    Settings("AutofillSuggestionFilled", _("Filling of autofill suggestions"), Mode.OFF),
    Settings("PopupClosed", _("Closing popups like hiding  suggestions of autofill"), Mode.OFF),
    Settings("AutofillSuggestionHideButton", _("Hiding  autofill suggestions"), Mode.OFF),
    Settings("UpdateNotification", _("Microsoft edge update availability"), Mode.SPEAK),
    Settings("PageZoom", _("Zoom changes"), Mode.SPEAK),
    Settings(
        "ShowSuggestions",
        _("Show suggestions while typing in addressbar"),
        Mode.SPEAK,
        kind=Kind.TOGGLE,
    ),
    Settings("RemoveSuggestion", _("Removing a suggestion"), Mode.SPEAK),
    Settings("ContentSettingNotification", _("Content setting notifications"), Mode.SPEAK),
    Settings("ExcelAutofillSuggestionTriggered", _("Triggerring of autofill suggestions"), Mode.SPEAK),
    Settings("EnteringFullscreen", _("Entering full screen"), Mode.SPEAK),
    Settings("ExitingFullscreen", _("Exiting full screen"), Mode.SPEAK),
    Settings("ShyUIVisible", _("Showing of toolbars in full screen"), Mode.OFF),
    Settings("ShyUIHidden", _("Hiding of toolbars in full screen"), Mode.OFF),
]


def unchanged(value):
    return value


def _modeSpec(setting):
    modes = ", ".join(repr(mode.value) for mode in MODES)
    return f"option({modes}, default={setting.defaultMode.value!r})"


class Field(NamedTuple):
    name: str
    spec: str | Callable
    default: Callable
    load: Callable = unchanged
    dump: Callable = unchanged

    def specFor(self, setting):
        return self.spec(setting) if callable(self.spec) else self.spec


FIELDS = (
    Field("mode", _modeSpec, lambda: Mode.SPEAK, Mode.fromConfig, lambda mode: mode.value),
    Field("useCustomMessage", "boolean(default=false)", bool),
    Field("customMessage", 'string(default="")', str),
    Field("beepPattern", "string_list(default=list())", list, deserializePattern, serializePattern),
    Field("waveFile", 'string(default="")', str),
    Field("waveVolume", "integer(0, 100, default=100)", lambda: 100),
)


class EventConfig:
    def __init__(self, **values):
        for field in FIELDS:
            setattr(self, field.name, values.get(field.name, field.default()))

    @classmethod
    def fromConfig(cls, section):
        if isinstance(section, (str, bool)):
            return cls(mode=Mode.OFF if _isFalse(section) else Mode.SPEAK)
        return cls(**{field.name: field.load(section[field.name]) for field in FIELDS})

    def save(self, section):
        for field in FIELDS:
            section[field.name] = field.dump(getattr(self, field.name))


class EventConfigs(dict):
    def __getattr__(self, name):
        try:
            return self[name]
        except KeyError:
            raise AttributeError(name) from None


def loadEventConfigs():
    migrateConfig()
    edgeConf = config.conf[addonName]
    return EventConfigs(
        (setting.configKey, EventConfig.fromConfig(edgeConf[setting.configKey])) for setting in settingItems
    )


def loadNotificationConfigs():
    configs = loadEventConfigs()
    return EventConfigs(
        (activityID, configs[setting.configKey])
        for setting in settingItems
        for activityID in setting.notificationIDs
    )


def saveEventConfigs(configs):
    edgeConf = config.conf[addonName]
    for setting in settingItems:
        configs[setting.configKey].save(edgeConf[setting.configKey])


def migrateConfig():
    knownKeys = {setting.configKey for setting in settingItems}
    for profile in config.conf.profiles:
        section = profile.get(addonName)
        if section is None:
            continue
        for key, value in list(section.items()):
            if isinstance(value, dict):
                continue
            try:
                del section[key]
                if key in knownKeys:
                    mode = Mode.OFF if _isFalse(value) else Mode.SPEAK
                    section[key] = {"mode": mode.value}
            except Exception:
                log.error(f"Could not migrate the configuration of {key}", exc_info=True)


def _isFalse(value):
    if isinstance(value, str):
        return value.strip().lower() in ("false", "no", "off", "0")
    return not value


config.conf.spec[addonName] = {setting.configKey: setting.configSpec for setting in settingItems}
