# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

import array
import os
import threading
import wave

from logHandler import log
import nvwave

SAMPLE_TYPES = {8: "B", 16: "h", 32: "i"}

_lock = threading.Lock()
_requested = threading.Event()
_request = None
_thread = None
_player = None
_playerFormat = None


def playFile(path, volume=100):
    global _request
    if not path or not os.path.isfile(path):
        log.warning(f"Cannot play the missing wave file {path!r}")
        return False
    with _lock:
        _request = (path, volume)
    if _player is not None:
        _player.stop()
    _requested.set()
    _startThread()
    return True


def _startThread():
    global _thread
    if _thread is None or not _thread.is_alive():
        _thread = threading.Thread(name=f"{__name__}.playRequested", target=_playRequested, daemon=True)
        _thread.start()


def _playRequested():
    global _request
    while True:
        _requested.wait()
        _requested.clear()
        with _lock:
            request, _request = _request, None
        if request is None:
            continue
        try:
            _play(*request)
        except Exception:
            log.error(f"Could not play the wave file {request[0]!r}", exc_info=True)


def _play(path, volume):
    global _player, _playerFormat
    with wave.open(path, "r") as waveFile:
        fileFormat = (
            waveFile.getnchannels(),
            waveFile.getframerate(),
            waveFile.getsampwidth() * 8,
        )
        frames = waveFile.readframes(waveFile.getnframes())
    if _player is None or fileFormat != _playerFormat:
        channels, samplesPerSec, bitsPerSample = fileFormat
        _player = nvwave.WavePlayer(
            channels=channels,
            samplesPerSec=samplesPerSec,
            bitsPerSample=bitsPerSample,
            wantDucking=False,
            purpose=nvwave.AudioPurpose.SOUNDS,
        )
        _playerFormat = fileFormat
    _player.feed(_atVolume(frames, fileFormat[2], volume))
    _player.idle()


def _atVolume(frames, bitsPerSample, volume):
    level = min(max(volume, 0), 100) / 100
    if level == 1:
        return frames
    sampleType = SAMPLE_TYPES.get(bitsPerSample)
    if sampleType is None:
        log.debugWarning(f"Cannot change the volume of {bitsPerSample} bit audio")
        return frames
    try:
        samples = array.array(sampleType, frames)
    except ValueError:
        log.debugWarning(f"Cannot change the volume of {len(frames)} bytes of audio", exc_info=True)
        return frames
    if sampleType == "B":
        samples[:] = array.array(sampleType, (round(128 + (sample - 128) * level) for sample in samples))
    else:
        samples[:] = array.array(sampleType, (round(sample * level) for sample in samples))
    return samples.tobytes()
