# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

from .panel import MSEdgeDiscardAnnouncementsPanel

__all__ = ["MSEdgeDiscardAnnouncementsPanel"]
