# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

import addonHandler
import gui
import wx

from .. import beeps

addonHandler.initTranslation()

STEP_FIELDS = {
    # Translators: The label of a control to choose the pitch of a beep.
    "frequency": (_("Fre&quency (Hz)"), beeps.MIN_FREQUENCY, beeps.MAX_FREQUENCY),
    # Translators: The label of a control to choose how long a beep lasts.
    "length": (_("&Length (ms)"), beeps.MIN_LENGTH, beeps.MAX_LENGTH),
    # Translators: The label of a control to choose the volume of a beep in the left channel.
    "leftVolume": (_("L&eft volume (%)"), 0, beeps.MAX_VOLUME),
    # Translators: The label of a control to choose the volume of a beep in the right channel.
    "rightVolume": (_("&Right volume (%)"), 0, beeps.MAX_VOLUME),
    # Translators: The label of a control to choose the silence following a beep.
    "pause": (_("&Pause after this beep (ms)"), 0, beeps.MAX_PAUSE),
}


def describeStep(step):
    # Translators: How one beep of a beep pattern is presented in the list of beeps.
    return _(
        "{frequency} Hz, {length} ms, left {leftVolume}%, right {rightVolume}%, pause {pause} ms"
    ).format(**step._asdict())


class Dialog(wx.Dialog):
    initialFocus = None

    def __init__(self, parent, title):
        super().__init__(parent, title=title)
        mainSizer = wx.BoxSizer(wx.VERTICAL)
        sHelper = gui.guiHelper.BoxSizerHelper(self, orientation=wx.VERTICAL)
        self.makeContent(sHelper)
        sHelper.addDialogDismissButtons(self.CreateButtonSizer(wx.OK | wx.CANCEL))
        mainSizer.Add(sHelper.sizer, border=gui.guiHelper.BORDER_FOR_DIALOGS, flag=wx.ALL)
        mainSizer.Fit(self)
        self.SetSizer(mainSizer)
        if self.initialFocus is not None:
            self.initialFocus.SetFocus()
        self.CentreOnScreen()

    def makeContent(self, sHelper):
        raise NotImplementedError

    def addButton(self, buttonHelper, label, handler):
        button = buttonHelper.addButton(self, label=label)
        button.Bind(wx.EVT_BUTTON, handler)
        return button


class BeepStepDialog(Dialog):
    def __init__(self, parent, step=beeps.DEFAULT_STEP):
        self.initialStep = step
        # Translators: The title of the dialog to add or edit one beep of a beep pattern.
        super().__init__(parent, _("Beep"))

    def makeContent(self, sHelper):
        self.fieldEdits = {}
        for name, (label, minimum, maximum) in STEP_FIELDS.items():
            self.fieldEdits[name] = sHelper.addLabeledControl(
                label,
                wx.SpinCtrl,
                min=minimum,
                max=maximum,
                initial=getattr(self.initialStep, name),
            )
        buttonHelper = gui.guiHelper.ButtonHelper(wx.HORIZONTAL)
        # Translators: The label of a button to hear the beep which is being edited.
        self.addButton(buttonHelper, _("&Test"), lambda event: beeps.playPattern([self.step]))
        sHelper.addItem(buttonHelper)
        self.initialFocus = self.fieldEdits[next(iter(STEP_FIELDS))]

    @property
    def step(self):
        return beeps.BeepStep(**{name: edit.Value for name, edit in self.fieldEdits.items()})


class BeepPatternDialog(Dialog):
    def __init__(self, parent, settingLabel, pattern):
        self.pattern = list(pattern)
        # Translators: The title of the dialog to build a beep pattern, {name} is the notification.
        super().__init__(parent, _("Beeps for {name}").format(name=settingLabel))

    def makeContent(self, sHelper):
        self.beepList = sHelper.addLabeledControl(
            # Translators: The label of the list of beeps played for a notification.
            _("&Beeps"),
            wx.ListBox,
            choices=[describeStep(step) for step in self.pattern],
        )
        self.beepList.Bind(wx.EVT_LISTBOX, lambda event: self.updateButtonStates())
        self.beepList.Bind(wx.EVT_LISTBOX_DCLICK, self.onEdit)
        buttonHelper = gui.guiHelper.ButtonHelper(wx.HORIZONTAL)
        # Translators: The label of a button to add a beep to the pattern.
        self.addBeepButton = self.addButton(buttonHelper, _("&Add..."), self.onAdd)
        # Translators: The label of a button to change the selected beep of the pattern.
        self.editButton = self.addButton(buttonHelper, _("&Edit..."), self.onEdit)
        # Translators: The label of a button to delete the selected beep from the pattern.
        self.removeButton = self.addButton(buttonHelper, _("&Remove"), self.onRemove)
        # Translators: The label of a button to play the selected beep earlier in the pattern.
        self.moveUpButton = self.addButton(buttonHelper, _("Move &up"), lambda event: self.onMove(-1))
        # Translators: The label of a button to play the selected beep later in the pattern.
        self.moveDownButton = self.addButton(buttonHelper, _("Move &down"), lambda event: self.onMove(1))
        # Translators: The label of a button to hear the whole beep pattern.
        self.playButton = self.addButton(
            buttonHelper, _("&Play pattern"), lambda event: beeps.playPattern(self.pattern)
        )
        sHelper.addItem(buttonHelper)
        self.updateBeepList()
        self.initialFocus = self.beepList

    def updateBeepList(self, selection=0):
        self.beepList.Set([describeStep(step) for step in self.pattern])
        if self.pattern:
            self.beepList.Selection = min(selection, len(self.pattern) - 1)
        self.updateButtonStates()

    def updateButtonStates(self):
        selection = self.beepList.Selection
        for button in (self.editButton, self.removeButton):
            button.Enable(selection != wx.NOT_FOUND)
        self.moveUpButton.Enable(selection > 0)
        self.moveDownButton.Enable(selection != wx.NOT_FOUND and selection < len(self.pattern) - 1)
        self.playButton.Enable(bool(self.pattern))

    def editStep(self, step):
        with BeepStepDialog(self, step) as dialog:
            return dialog.step if dialog.ShowModal() == wx.ID_OK else None

    def onAdd(self, event):
        step = self.editStep(beeps.DEFAULT_STEP)
        if step is None:
            return
        self.pattern.append(step)
        self.updateBeepList(len(self.pattern) - 1)
        self.beepList.SetFocus()

    def onEdit(self, event):
        selection = self.beepList.Selection
        if selection == wx.NOT_FOUND:
            return
        step = self.editStep(self.pattern[selection])
        if step is None:
            return
        self.pattern[selection] = step
        self.updateBeepList(selection)
        self.beepList.SetFocus()

    def onRemove(self, event):
        selection = self.beepList.Selection
        if selection == wx.NOT_FOUND:
            return
        del self.pattern[selection]
        self.updateBeepList(selection)
        self.beepList.SetFocus()

    def onMove(self, offset):
        selection = self.beepList.Selection
        target = selection + offset
        if selection == wx.NOT_FOUND or not 0 <= target < len(self.pattern):
            return
        self.pattern[selection], self.pattern[target] = self.pattern[target], self.pattern[selection]
        self.updateBeepList(target)
        self.beepList.SetFocus()
