# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022-2026 Beka Gozalishvili
# Released under GPL 2

import os
from typing import Callable, NamedTuple

import addonHandler
import gui
import wx

from ..beeps import DEFAULT_STEP
from ..donate_dialog import requestDonations
from ..settings import (
    MODES,
    Kind,
    Mode,
    addonSummary,
    loadEventConfigs,
    saveEventConfigs,
    settingItems,
    unchanged,
)
from ..sounds import playFile
from .beepDialogs import BeepPatternDialog

addonHandler.initTranslation()

CHANGE_EVENTS = {
    wx.Choice: wx.EVT_CHOICE,
    wx.CheckBox: wx.EVT_CHECKBOX,
    wx.TextCtrl: wx.EVT_TEXT,
    wx.SpinCtrl: wx.EVT_SPINCTRL,
}


def _isMode(setting, eventConfig, mode):
    return setting.kind == Kind.ACTION and eventConfig.mode == mode


class Control(NamedTuple):
    field: str
    label: str
    control: type
    applies: Callable
    arguments: dict = {}
    fromControl: Callable = unchanged
    toControl: Callable = unchanged


CONTROLS = (
    Control(
        "mode",
        # Translators: The label of the combo box to choose what NVDA does with the selected notification.
        _("&Action"),
        wx.Choice,
        lambda setting, eventConfig: setting.kind == Kind.ACTION,
        arguments={"choices": [mode.displayString for mode in MODES]},
        fromControl=MODES.__getitem__,
        toControl=MODES.index,
    ),
    Control(
        "mode",
        # Translators: The label of a check box to turn the selected setting on or off.
        _("Ena&bled"),
        wx.CheckBox,
        lambda setting, eventConfig: setting.kind == Kind.TOGGLE,
        fromControl=lambda checked: Mode.SPEAK if checked else Mode.OFF,
        toControl=lambda mode: mode != Mode.OFF,
    ),
    Control(
        "useCustomMessage",
        # Translators: The label of a check box to speak a message of your own instead of Edge's one.
        _("Speak a &custom message"),
        wx.CheckBox,
        lambda setting, eventConfig: _isMode(setting, eventConfig, Mode.SPEAK),
    ),
    Control(
        "customMessage",
        # Translators: The label of the field holding the message to speak for the selected notification.
        _("&Message"),
        wx.TextCtrl,
        lambda setting, eventConfig: (
            _isMode(setting, eventConfig, Mode.SPEAK) and eventConfig.useCustomMessage
        ),
    ),
    Control(
        "waveFile",
        # Translators: The label of the field holding the wave file played for the notification.
        _("Wave &file"),
        wx.TextCtrl,
        lambda setting, eventConfig: _isMode(setting, eventConfig, Mode.WAVE),
    ),
    Control(
        "waveVolume",
        # Translators: The label of a control to choose how loud the wave file is played.
        _("Wave file &volume (%)"),
        wx.SpinCtrl,
        lambda setting, eventConfig: _isMode(setting, eventConfig, Mode.WAVE),
        arguments={"min": 0, "max": 100},
    ),
)


class MSEdgeDiscardAnnouncementsPanel(gui.settingsDialogs.SettingsPanel):
    title = addonSummary

    def makeSettings(self, sizer):
        self.eventConfigs = loadEventConfigs()
        sHelper = gui.guiHelper.BoxSizerHelper(self, sizer=sizer)
        self.settingList = sHelper.addLabeledControl(
            # Translators: The label of the list of Microsoft Edge notifications.
            _("&Notification"),
            wx.ListBox,
            choices=[setting.label for setting in settingItems],
        )
        self.settingList.Bind(wx.EVT_LISTBOX, lambda event: self.updateControls())
        self.controls = {}
        for spec in CONTROLS:
            control = self.makeControl(sHelper, spec)
            control.Bind(CHANGE_EVENTS[spec.control], self.onControlChange)
            self.controls[control] = spec
        buttonHelper = gui.guiHelper.ButtonHelper(wx.HORIZONTAL)
        self.buttons = {}
        for label, handler, applies in (
            (
                # Translators: The label of a button opening the dialog to build the beeps of a notification.
                _("Configure b&eeps..."),
                self.onConfigureBeeps,
                lambda setting, eventConfig: _isMode(setting, eventConfig, Mode.BEEPS),
            ),
            (
                # Translators: The label of a button to choose the wave file played for the notification.
                _("&Browse..."),
                self.onBrowseWaveFile,
                lambda setting, eventConfig: _isMode(setting, eventConfig, Mode.WAVE),
            ),
            (
                # Translators: The label of a button to hear the wave file played for the notification.
                _("&Play file"),
                self.onPlayWaveFile,
                lambda setting, eventConfig: (
                    _isMode(setting, eventConfig, Mode.WAVE) and bool(eventConfig.waveFile)
                ),
            ),
        ):
            button = buttonHelper.addButton(self, label=label)
            button.Bind(wx.EVT_BUTTON, handler)
            self.buttons[button] = applies
        sHelper.addItem(buttonHelper)
        supportHelper = gui.guiHelper.ButtonHelper(wx.HORIZONTAL)
        # Translators: The label of a button to support the author of the add-on with a donation.
        supportButton = supportHelper.addButton(self, label=_("&Support the author..."))
        supportButton.Bind(wx.EVT_BUTTON, self.onSupportAuthor)
        sHelper.addItem(supportHelper)
        self.settingList.Selection = 0
        self.updateControls()

    def makeControl(self, sHelper, spec):
        if spec.control is wx.CheckBox:
            return sHelper.addItem(wx.CheckBox(self, label=spec.label))
        return sHelper.addLabeledControl(spec.label, spec.control, **spec.arguments)

    @property
    def currentSetting(self):
        return settingItems[self.settingList.Selection]

    @property
    def currentEventConfig(self):
        return self.eventConfigs[self.currentSetting.configKey]

    def updateControls(self):
        setting, eventConfig = self.currentSetting, self.currentEventConfig
        for control, spec in self.controls.items():
            self.showValue(control, spec.toControl(getattr(eventConfig, spec.field)))
            control.Enable(spec.applies(setting, eventConfig))
        for button, applies in self.buttons.items():
            button.Enable(applies(setting, eventConfig))

    def showValue(self, control, value):
        if isinstance(control, wx.Choice):
            control.Selection = value
        elif isinstance(control, wx.TextCtrl):
            if control.Value != value:
                control.ChangeValue(value)
        else:
            control.Value = value

    def shownValue(self, control):
        return control.Selection if isinstance(control, wx.Choice) else control.Value

    def onControlChange(self, event):
        spec = self.controls[event.EventObject]
        eventConfig = self.currentEventConfig
        setattr(eventConfig, spec.field, spec.fromControl(self.shownValue(event.EventObject)))
        if eventConfig.mode == Mode.BEEPS and not eventConfig.beepPattern:
            eventConfig.beepPattern.append(DEFAULT_STEP)
        self.updateControls()

    def onBrowseWaveFile(self, event):
        eventConfig = self.currentEventConfig
        with wx.FileDialog(
            self,
            # Translators: The title of the dialog to choose the wave file played for a notification.
            message=_("Choose a wave file"),
            # Translators: The filter of the dialog to choose a wave file.
            wildcard=_("Wave files") + " (*.wav)|*.wav",
            defaultDir=os.path.dirname(eventConfig.waveFile),
            defaultFile=os.path.basename(eventConfig.waveFile),
            style=wx.FD_OPEN | wx.FD_FILE_MUST_EXIST,
        ) as dialog:
            if dialog.ShowModal() == wx.ID_OK:
                eventConfig.waveFile = dialog.Path
                self.updateControls()

    def onPlayWaveFile(self, event):
        eventConfig = self.currentEventConfig
        playFile(eventConfig.waveFile, eventConfig.waveVolume)

    def onConfigureBeeps(self, event):
        eventConfig = self.currentEventConfig
        with BeepPatternDialog(self, self.currentSetting.label, eventConfig.beepPattern) as dialog:
            if dialog.ShowModal() == wx.ID_OK:
                eventConfig.beepPattern = dialog.pattern

    def onSupportAuthor(self, event):
        requestDonations(addonSummary, self)

    def onSave(self):
        saveEventConfigs(self.eventConfigs)
