# MSEdgeDiscardAnnouncements: An appModule to discard some of notifications generated by Microsoft Edge
# Copyright (C) 2022 Beqa Gozalishvili
# Released under GPL 2

import appModuleHandler
from collections import namedtuple
import config
import gui
import wx

Settings = namedtuple("Settings", "configKey, label, defaultValue")
settingItems = [
    Settings("PageLoading", _("Announce loading of pages"), "boolean(default=false)"),
    Settings("RefreshingPage", _("Announce page refresh"), "boolean(default=false)"),
    Settings("ClosingTab", _("Announce closing of tab"), "boolean(default=false)"),
    Settings("OpeningNewTab", _("Announce Opening of new tab"), "boolean(default=false)"),
    Settings("OpeningWindow", _("Announce window opening"), "boolean(default=false)")
    Settings("HubDownloadsNewDownload", _("Announce starting file download"), "boolean(default=true)")
    Settings("HubDownloadsCompleteState", _("Announce download completion"), "boolean(default=true)")
    Settings("GoingBack", _("Announce navigating back"), "boolean(default=false)")
    ]

config.conf.spec["MSEdgeDiscardAnnouncements"] = {setting.configKey: setting.defaultValue for setting in settingItems}

class AppModule(appModuleHandler.AppModule):
    activityIDs = []

    def __init__(self, processID, appName):
        super(AppModule, self).__init__(processID, appName)
        categoryClasses = gui.settingsDialogs.NVDASettingsDialog.categoryClasses
        if not (MSEdgeDiscardAnnouncementsPanel in categoryClasses):
            categoryClasses.append(MSEdgeDiscardAnnouncementsPanel)

    def terminate(self):
        super(AppModule, self).terminate()
        gui.settingsDialogs.NVDASettingsDialog.categoryClasses.remove(MSEdgeDiscardAnnouncementsPanel)

    def getActivityIDsFromConfig(self):
        edgeConf = config.conf["MSEdgeDiscardAnnouncements"]
        self.activityIDs = [k for k, v in edgeConf.items() if type(v) == bool and v == False]

    def event_appModule_gainFocus(self):
        self.getActivityIDsFromConfig()

    def event_UIA_notification(self, obj, nextHandler, activityId=None, **kwargs):
        if activityId in self.activityIDs: return
        nextHandler()

class MSEdgeDiscardAnnouncementsPanel(gui.settingsDialogs.SettingsPanel):
    title = "Microsoft Edge discard announcements"

    def makeSettings(self, sizer):
        self.config = config.conf["MSEdgeDiscardAnnouncements"]
        self.helper = gui.guiHelper.BoxSizerHelper(self, sizer=sizer)
        for setting in settingItems:
                widget = self.helper.addItem(wx.CheckBox(self, label=setting.label, name=setting.configKey))
                widget.SetValue(self.config[setting.configKey])

    def onSave(self):
        for child in self.helper.sizer.GetChildren():
            widget = child.GetWindow()
            if isinstance(widget, wx.CheckBox):
                self.config[widget.Name] = widget.IsChecked()
